### ISSUE TITLE
Bad incomplete swap status

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/BarterDEX#101]
When alice claims bob's deposit and is not allowed to claim alice payment, the history shows "Invalid Date"
![capture](https://user-images.githubusercontent.com/21057518/35892528-51cb9746-0b6f-11e8-925f-bc3bd99f938f.JPG)

**Comment by TheComputerGenie** [comment]
Also, it leaves exchange trade status tab blank and locks up balance section
![capture](https://user-images.githubusercontent.com/21057518/35892607-b5ca16a0-0b6f-11e8-8506-a1210fb16811.JPG)

**Comment by siulynot** [comment]
Is this fixed in the latest release?
