### ISSUE TITLE
Make Depoist doesn't work correctly

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/BarterDEX#11]
When user attempts to place an order and there are no UTXOs that are close in size, user is prompted with a dialog box asking if they want the GUI to make a "correct" deposit/UTXO
![makedeposit](https://user-images.githubusercontent.com/21057518/34326424-29a65bbe-e871-11e7-88e7-d8b1cb2afde7.JPG)

Expected: User would have a new UTXO of 22.4

Actual:  `dustcombine` creates a singular UTXO and user is charged tx fee for nothing
```
combine last vout 22.40010000 with change 2209.08846574
LP_withdraw.KMD {"method":"withdraw","coin":"KMD","outputs":[{"RUdNzKNzsyebRdDoprrkDZum1PkGoMY4RP":22.40010000}]} -> 331ed8649db7f9655576861db33b2e97968186e68b2c4a9acfc55ef69e6e3f39
```
[331ed8649db7f9655576861db33b2e97968186e68b2c4a9acfc55ef69e6e3f39](https://kmd.explorer.supernet.org/tx/331ed8649db7f9655576861db33b2e97968186e68b2c4a9acfc55ef69e6e3f39)

**Comment by satindergrewal** [comment]
updated to this function must have fixed this issue. please comment on this issue again if still exists.
