### ISSUE TITLE
can not trade in barterDEX

### ISSUE THREAD

**Issue by Darren9898** [KomodoPlatform/BarterDEX#120]
I try to trade in barterDEX in Windows 10 V0.8.8-rc,  I had deposited 1500 BTCZ days ago, but can't make any order. always pop up  deposit screen.  any user guide for help.
![barterdex](https://user-images.githubusercontent.com/29515632/36603551-212933c4-1889-11e8-8997-b3bfcc59a76e.PNG)

**Comment by TheComputerGenie** [comment]
![operr](https://user-images.githubusercontent.com/21057518/36640913-270dc312-19ed-11e8-8cbd-0d06cb0625e2.jpg)

**Comment by himu007** [comment]
Darren, you need utxo pair to swap in barterdex, not the total balance. Join #tradebots channel in our [slack](https://join.slack.com/t/komodo-platform/shared_invite/enQtMzI3MTc2MjAwNDUzLTkwN2Q3ZDkxMDlhMTY5NTg0NWI1MWMxY2YwMDRiYzNkM2JiYTc2MGRlZTc5YjlkNThkMWZhYzAyYjQ0N2UwNjU) for support and more info.
