### ISSUE TITLE
0conf deposit minimum 10.0001 KMD - urgent

### ISSUE THREAD

**Issue by himu007** [KomodoPlatform/BarterDEX#122]
Please make the 0conf deposit to use minimum 10.0001 KMD. Otherwise, users will not be able to collect interest while claiming their deposit.
Also, changes needed in the description as well.
![image](https://user-images.githubusercontent.com/8881040/36641383-b8357d2e-1a26-11e8-99a2-9a1a1849b8dd.png)

**Comment by satindergrewal** [comment]
pushed fix: https://github.com/KomodoPlatform/BarterDEX/commit/9305a5657babb6bb73982b5c273f7a7a652e2019
