### ISSUE TITLE
UTXO Inventory screen should prevent negative numbers

### ISSUE THREAD

**Issue by leto** [KomodoPlatform/BarterDEX#126]
![negative_btch](https://user-images.githubusercontent.com/30298/36825496-b890d762-1cbc-11e8-9837-660f61f3819e.png)

One can make the "Make inventory" button clickable by entering negative numbers even when you don't have enough in total to make inventory

Experienced this on 0.8.8-rc

**Comment by satindergrewal** [comment]
Thanks for reporting. Condition added to this commit: https://github.com/KomodoPlatform/BarterDEX/commit/948d987e46393a2282b1c7e7c664d9dd1b31ae5a
