### ISSUE TITLE
Submitted offer but it has 0 UTXOs

### ISSUE THREAD

**Issue by hanzac** [KomodoPlatform/BarterDEX#130]
What's the problem, it did make the offer and list in the orders list but show 0 UTXOs.

**Comment by hanzac** [comment]
Now I can make some trades succeeded. But still not comfortable about the UTXOs. Can we manually select the UTXO to place into the order? This will allow no error happened.

**Comment by siulynot** [comment]
please update to 0.8.11. 
 Since an order match process will happen a specific utxo can not be chosen to sell. If you use auto repeeat with fixed price you will have all utxos available to be selected for a swap.
