### ISSUE TITLE
Not Receiving Coins on BarterDEX

### ISSUE THREAD

**Issue by iMMaFieNd** [KomodoPlatform/BarterDEX#131]
Hello,

I sent 49.9 ZClassic Coins to the Barterdex address from my Electrum Wallet (not full-node) to the Barterdex smart address but they are not showing up. Anything I did wrong? I added both KMD and ZCL to the Barterdex wallet in order to exchange and ran both the Agama wallet (native) and Electrum but it is not working. Did I do something wrong? It is my first time testing out and I appreciate any help.

Thanks,

**Comment by gonzalezea** [comment]
Same here but with HUSH. Sent 4 transactions (100+conf) to address in electrum mode & only first one was received. Seems a syncro problem with network. So far haven't found any msg in log that give some clue or how to resync.

[HUSH address](https://explorer.myhush.org/address/t1eUctvouuyo93KzAv5PoCVVYX8w8gh4pem)

Ubuntu 16.04.4 x64
Barterdex 0.8.9-rc
