### ISSUE TITLE
Buttons not giving feedback 

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/BarterDEX#135]
On various occasions including
-when executing an order
-refreshing
-press any button
Nothing happens. There is no feedback to the user. It's confusing and often there are things happening in the background.

**Comment by satindergrewal** [comment]
-Executing order gives the info messages as it triggers the steps. Trade status tab previously been disabled auto refresh. that now auto refresh after recent git commits.
-refresh buttons in app are updated to show info message on button push.
