### ISSUE TITLE
Remove Uneccesary Charts and Improve Layout

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/BarterDEX#136]
-Removal of charts and improvement of layout. (siddharta has been working on a simple layout that all guis will share to create familarity. 

If the task is too lengthy, then a simple removal of the charts and improvement of the tabs would work. 

If you look at the app without the charts it would be very slim.

**Comment by satindergrewal** [comment]
Disabled charts setting implemented in this commit: https://github.com/KomodoPlatform/BarterDEX/commit/32c1fceb7e5a6b901cccce8e60e729983c081199
