### ISSUE TITLE
utxo splitter 

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/BarterDEX#138]
-utxo splitter gets stuck and after you split sometimes it won't let you sent out. I have to import my seed into Agama and get the funds out or remerge them.

**Comment by satindergrewal** [comment]
splitter issues fixed in this commit: https://github.com/KomodoPlatform/BarterDEX/commit/78d85430ce96512e718341d6323314643cfa25b1

Must have fixed your issue in it too.
