### ISSUE TITLE
Realtime statistics is not realtime

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/BarterDEX#141]
I have made many swaps, with no feedback in the gui until i navigate to dashboard, and go back into the exchange tab. This means the gui isn't fetching or showing data properly. if someone makes a swap, instead of visual ques that don't necessarily work, how about showing backend output in a pretty text form?
this way we can see exactly what is happening instead of guessing.

**Comment by satindergrewal** [comment]
fixed in this commit: https://github.com/KomodoPlatform/BarterDEX/commit/78d85430ce96512e718341d6323314643cfa25b1
