### ISSUE TITLE
KMD isn't selected automatically when you login

### ISSUE THREAD

**Issue by ptyx11** [KomodoPlatform/BarterDEX#145]
<img width="1276" alt="screen shot 2018-03-07 at 9 46 48 pm" src="https://user-images.githubusercontent.com/32718517/37132012-111d0f92-2251-11e8-9ff1-f88c20595d2c.png">
No coins are selected when you login. Also there is no persistance of previous coins.

**Comment by ptyx11** [comment]
https://screencast-o-matic.com/watch/cFejffDoVY

**Comment by satindergrewal** [comment]
https://github.com/KomodoPlatform/BarterDEX/issues/29
