### ISSUE TITLE
native mode vs electrum mode documentation

### ISSUE THREAD

**Issue by givanse** [KomodoPlatform/BarterDEX#156]
Is there a write up somewhere that can help you make a more informed decision between adding coins in native mode or electrum mode?

Maybe even add a tooltip on the UI switch? A short reminder of what the tradeoffs are would be nice. Something along the lines of:
```native: run your own full node, store your own copy of the blockchain.```
```electrum: connect to remote full nodes```

**Comment by siulynot** [comment]
Tool tips are going to be added once we have the rebase of the code done.

**Comment by tofutim** [comment]
Any progress on the tool tips? Regarding electrum and remote full nodes, is there a way to verify who is running the remote full nodes? Will it be the seed nodes from the coin itself?

**Comment by VhaTer** [comment]
+1
