### ISSUE TITLE
0 balance during utxo splitting should display 'Please Wait' (UI)

### ISSUE THREAD

**Issue by ch4ot1c** [KomodoPlatform/BarterDEX#158]
In electrum mode, I used the Inventory UTXO Splitter. Then, upon restarting the app, it displayed a 0 balance of my coin (in portfolio, exchange, and inventory) - but after refreshing maybe 5 minutes later, the balance re-appeared.

**Comment by siulynot** [comment]
When you split utxos you are effectively making transactions to yourself. To be able to trade you need to wait for 1 confirmation to be able to trade. So its not a timing matter, but a confirmation matter.

**Comment by ch4ot1c** [comment]
Certainly; that intermediate period needs to be accounted for the in the UI.
