### ISSUE TITLE
Update Title

### ISSUE THREAD

**Issue by polycryptoblog** [KomodoPlatform/BarterDEX#16]
Not sure how to update title via pull request,    but the title needs to be updated to something more SEO friendly than  BarterDEX GUI :  https://barterdex.com

Try this:

BarterDEX:  The World's First Decentralized Atomic Swap Based Exchange by Komodo Platform
Official Site : https://www.komodoplatform.com/en/technology/barterdex

**Comment by satindergrewal** [comment]
updated readme file.
please close this issue if all is good.
