### ISSUE TITLE
BTCP balance not showing on BarterDEX

### ISSUE THREAD

**Issue by paulofoerster** [KomodoPlatform/BarterDEX#160]
Hi guys, I transferred some BTCP (Bitcoin Private) 12 hours ago to the exchange and nothing is showing up. I see it confirmed and the balance in the wallet via browser but it doesnt show in the platform, any ideas?

And since I dont have access to the private keys of the new wallet address generated at BarterDEX my coins are stuck.

The transaction is confirmed and the balance in the native account generated by BarterDEX, but it doesnt show in the platform.

Can you guys please give me some help?

Best regards,

Paulo Foerster

**Comment by siulynot** [comment]
Are you using electrum? Maybe try to use native and see if that works.

**Comment by Fritzerton** [comment]
I've got the same issue. I'm using the native wallet on MacOS. Been 3 days and over 1200 confirmations. Got a response from the support group suggesting deleting the coins.json file but that didn't make a difference. Also tried installing on another Mac but it did the same thing.

**Comment by Fritzerton** [comment]
I just got another email from them that said download the newest version 8.12 and it’s supposed to fix this issue. I do t have my laptop with me but I’ll let you know after I try it

**Comment by paulofoerster** [comment]
Hi guys, good news, I used the latest version 8.12, and I was able to transfer my balance out. But keep in mind I wasn't able to see my balance from my mac, I had to do it via windows. So don't freak out, it was a bug and they are working on it.
