### ISSUE TITLE
ETH withdrawn

### ISSUE THREAD

**Issue by CHMEX** [KomodoPlatform/BarterDEX#169]
![image](https://user-images.githubusercontent.com/33424502/37727212-88219fcc-2d37-11e8-8c68-b2e8b2418419.png)

When sending ETH / Tokens from the GUI the 0.0001 fee does not need to be applied as in ETH the full amount is sent (the fee is paid from your balance but not from the UTXO [there are no UXTO in ETH]): here is a sample transction with above parameters:
etherscan.io/tx/0x29fccae8b2015769b5c6536c84451f96aecd48338a400537e77ee78ae85bf0e7

BTW: it works!!

**Comment by satindergrewal** [comment]
https://github.com/KomodoPlatform/BarterDEX/commit/fb27483bba2d3ffdd03e7b136eed83274f99e27c
