### ISSUE TITLE
ZEC & HUSH show same receiving address

### ISSUE THREAD

**Issue by gonzalezea** [KomodoPlatform/BarterDEX#175]
When added ZEC (native mode) it shows same address as HUSH (electrum) as in [image](https://imgur.com/soS08of). The address really belongs to HUSH and is working fine [(HUSH addr)](https://explorer.myhush.org/address/t1eUctvouuyo93KzAv5PoCVVYX8w8gh4pem). Adding ZEC in electrum mode shows same address. Same result when deleted all coins & restart. ZEC address should be any of these:
```

 root@minerland:~# zcash-cli getaddressesbyaccount ""
 [
   "t1KsGM2UT1wrQyMVcpYZhwa62TFXmiLTHMo",
   "t1RYqcD7GpeGirx34RqPTScMnEZiQhqya9u"
 ]

```
Ubuntu 16.04.4 x64
Barterdex v.0.8.13-rc

**Comment by cipig** [comment]
Both coins have the same address format and the address is generated out of the same passphrase (the one you used to login), so this is normal. You will see more coins with the same addresses, eg KMD and all the assetchains.
