### ISSUE TITLE
Error happens when show ethereum inventory

### ISSUE THREAD

**Issue by hanzac** [KomodoPlatform/BarterDEX#211]
The balance is correct and not empty. But error happens in the console log:

Objecterror: "no coin"__proto__: Object
dex_SimpleActions.js:993 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.<anonymous> (dex_SimpleActions.js:993)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by TheComputerGenie** [comment]
That error is a logging issue that can be dealt with by commenting out dex_SimpleActions.js#L993

**Comment by himu007** [comment]
This issue should have been gone by now with newer versions. Closing this one now since no new occurrence of this issue.
