### ISSUE TITLE
Pigeon deposit arrived in the wallet but not visible on the GUI.

### ISSUE THREAD

**Issue by alexhasegan** [KomodoPlatform/BarterDEX#212]
Hi,
I send last night 3 transactions from my local Pigeon wallet to BarterDEX:
from:
PU5CmVSnmLBQkej3DdpUEnY8oHWiuyn4hf
to:
PL9ohvWzniVa56Xrwu544TCVmCzC4UTX4W
Amounts/tx ids:
2000 pgn
a5280c5c41e7e9d3890e32c8c0dd2a48d11c9201010f51bead4ceb33dcd888dc
1 pgn
07e84af9bb76a5cef0bf6f741479be0a1d3a0c2c33694efe511878dfb6ec423a
3 pgn
7fcb48bcd352469ebcd0abfdaf03445f4c4b9c6a67cfe800c7836bca40d3bfbe
None of these orders arrived in my BarterDEX account.
Please help!

**Comment by TheComputerGenie** [comment]
http://explorer.pigeoncoin.org/address/PL9ohvWzniVa56Xrwu544TCVmCzC4UTX4W
They are **all** there.

**Comment by TheComputerGenie** [comment]
The 1st thing you need to do is edit the title of your issue and make it accurate.
It arrived in your wallet, but is not visible in the GUI; those are not the same thing.

**Comment by alexhasegan** [comment]
ok, changed.
Next step?

**Comment by alexhasegan** [comment]
any updates?

**Comment by alexhasegan** [comment]
same problem on last version of barterdex.
How ca I solve it in order to have the PGN on my wallet?

**Comment by alexhasegan** [comment]
up

**Comment by cipig** [comment]
You have to make sure BarterDEX can connect to your Pigeon wallet. Your config file ~/.pigeon/pigeon.conf must have at least this entries:
```
server=1
rpcuser=someuser
rpcpassword=somepassword
```
The datadir (with the chain) must be in the default location (~/.pigeon under Linux).

**Comment by alexhasegan** [comment]
Solved!
Thanks.
