### ISSUE TITLE
Impossible to send Ethereum

### ISSUE THREAD

**Issue by Nekojitasama** [KomodoPlatform/BarterDEX#214]
![bug](https://user-images.githubusercontent.com/36922817/38700628-00e22326-3e9c-11e8-9f1e-4b2b1561a570.jpg)
impossible to send my ethereum, in electrum mode or native, UNDEFINED shows instead of the transaction code

**Comment by Nekojitasama** [comment]
can somebody at least say me how to get my ethereum private keys from barterdex?

**Comment by satindergrewal** [comment]
There's some update done to `marketmaker` in regard of ETH by core dev artem.
you will need latest `marketmaker` binaries in the app to test and check if your issue is resolved, as the reported issue is most likely a core `marketmaker` issue instead of UI issue.

@himu007 can help further on this.

**Comment by Nekojitasama** [comment]
Thanks, I will ask him.


________________________________
De : Satinder Grewal <notifications@github.com>
Envoyé : lundi 7 mai 2018 12:47
À : KomodoPlatform/BarterDEX
Cc : Nekojitasama; Author
Objet : Re: [KomodoPlatform/BarterDEX] Impossible to send Ethereum (#214)


There's some update done to marketmaker in regard of ETH by core dev artem.
you will need latest marketmaker binaries in the app to test and check if your issue is resolved, as the reported issue is most likely a core marketmaker issue instead of UI issue.

@himu007<https://github.com/himu007> can help further on this.

**Comment by chisNaN** [comment]
Hello @satindergrewal .
Please can you confirm that if we build barterdex like explained here
https://github.com/KomodoPlatform/KomodoPlatform/wiki/Installing-and-Using-Komodo-Platform-(barterDEX)

we should be able to solve this problem and transfer out the ETH ?

Thanks

**Comment by cipig** [comment]
I can confirm that BarterDEX-CLI can handle ERC20-withdraws, have done it many times, eg:

`curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"eth_withdraw\",\"coin\":\"ELD\",\"to\":\"0x4e623b150b847da59f064f7c7fcc9f787dae2229\",\"amount\":1}"`

Replace ELD with ETH, put the correct address in "to" and the desired amount and it works fine.

**Comment by cipig** [comment]
sending of ETH fixed in dev branch
