### ISSUE TITLE
Passphrase generator breaks: `bip39.generateMnemonic()` is undefined

### ISSUE THREAD

**Issue by bartwr** [KomodoPlatform/BarterDEX#224]
I try to generate a new passphrase.

## Expected behaviour: 

Generating a new passphrase works.

## Actual behaviour: 

Generating a new passphrase does not work.

![screenshot from 2018-04-21 00-04-59](https://user-images.githubusercontent.com/899234/39075756-ac59586c-44f7-11e8-961c-f391fe854fae.png)

## Steps to reproduce:

- Open your terminal
- Navigate to the BarterDEX directory
- `git checkout dev && git pull`
- `npm start`

The BarterDEX GUI will now open.

- Toggle Development Tools by clicking _View_ -> _Toggle Developers Tools_
- Click the "Generate a New Passphrase" button

Now, you have reproduced **the problem**: There is no passphrase generated.

And you have reproduced the **link to a solution**:

    Uncaught TypeError: Cannot read property 'generateMnemonic' of undefined
    at HTMLDocument.<anonymous> (ipc-actions.js:211)

![screenshot from 2018-04-21 00-03-33](https://user-images.githubusercontent.com/899234/39075720-7b76aac4-44f7-11e8-8d55-4401b65b6a20.png)

**Comment by satindergrewal** [comment]
<img width="1392" alt="screen shot 2018-05-07 at 8 43 28 pm" src="https://user-images.githubusercontent.com/12998093/39693194-5593ffe4-5237-11e8-934c-1ccfda172b86.png">

tried replicating on osx. couldn't replicate.

<img width="1680" alt="screen shot 2018-05-07 at 8 46 31 pm" src="https://user-images.githubusercontent.com/12998093/39693336-c1570276-5237-11e8-877e-958291637bde.png">

Tried in ubuntu linux too. unable to replicate.

used latest dev branch.

**Comment by himu007** [comment]
@bartwr which OS and device you are using? it works fine in my Ubuntu 16.04 laptop using latest dev branch.

![screenshot from 2018-05-07 10-36-25](https://user-images.githubusercontent.com/8881040/39695500-ad188cbc-51e2-11e8-8c67-e6af486bbc91.png)

**Comment by satindergrewal** [comment]
closing since it's not replicated.
