### ISSUE TITLE
Show Transfer history (send+receive funds)

### ISSUE THREAD

**Issue by gonzalezea** [KomodoPlatform/BarterDEX#225]
Beside popup windows after receiving or sending coins, there's no place to consult Tx id at least. Would be nice to have all info about transfer.

**Comment by satindergrewal** [comment]
Two things:
1. BarterDEX GUI is now being treated as *DEVELOPER REFERENCE*. It should display in the simplest form for 3rd party developers how the underlying `marketmaker` daemon which is providing the Decentralised Exchange (DEX) API is being used in a Graphical form. There is nothing out of the way fancy implemented in BarterDEX, unlike other codebases like dICO Apps and HyperDEX which are using many codebase and API set which is not actually from `marketmaker` API. BarterDEX however is solely relying on ONLY `marketmaker` API, and that is what makes it pure implimentation and a subject to refer to 3rd party developers to refer to it's codebase and get an idea how all the backend working parts fit together to make a Decentralised Exchange Application.
2. BarterDEX GUI is not a Wallet. For Wallet functionalities please use other wallet apps like Agama Wallet.

Hope this clears.
