### ISSUE TITLE
Desposit 0 BTCP

### ISSUE THREAD

**Issue by bibondz** [KomodoPlatform/BarterDEX#229]
I have Deposit BTCP to BarterDEX, It's require 3 minimum deposit, I follow the recommended method.
still 0 but Block Explorer show
https://explorer.btcprivate.org/address/b1S81CKMLv85yb4vdTovoS3uUeL2joGtgfU

**Comment by bibondz** [comment]
![image](https://user-images.githubusercontent.com/8419523/39505012-f030a792-4df9-11e8-8a7a-5de8ee92843a.png)

**Comment by himu007** [comment]
BTCP electrum server has issues. Please use native mode as @cipig mentioned.
