### ISSUE TITLE
How To Intergrate My Coin?

### ISSUE THREAD

**Issue by jared201** [KomodoPlatform/BarterDEX#230]
Hi,

Just a quick question, my coin is already integrated with BISQ. How do I integrated with BarterDEX?

Thanks!

**Comment by cipig** [comment]
Hi. If it is a erc20-token i need the contract address, if it is a coin, please tell me the link to the wallet source code. The name and ticker symbol would also be a useful information.

**Comment by jared201** [comment]
@cipig here it is:

Name: Tamadcoin
Symbol: TMC
Wallet: https://github.com/jared201/tamadcoin

**Comment by cipig** [comment]
Sorry, but BarterDEX does not support CryptoNote based coins. Maybe in a future version.
