### ISSUE TITLE
setting up barterdex on windows 7

### ISSUE THREAD

**Issue by BLenselink** [KomodoPlatform/BarterDEX#237]
I installed BarterDEX on Raspberry PI succesfully. Now I intend to install BarterDEX on Windows 7 in order to be able to use the GUI. I used https://github.com/DeckerSU/SuperNET/blob/dev-decker-dev/iguana/dexscripts.win32/how_to_use.md but I cannot locate the 1-cliend.cmd. Any suggestions where to find this cmd file?

**Comment by satindergrewal** [comment]
That's nice to know you testing BarterDEX on Raspberry Pi.

For windows, you don't need to do anything. the `marketmaker` binaries are already bundled with the BarterDEX. You can follow the ReadMe from BarterDEX repo and install it on Windows machine: https://github.com/KomodoPlatform/BarterDEX/blob/master/ReadMe.md

If you are talking about manually compiling `marketmaker` for windows and using the command line BarterDEX, then it's good you follow @DeckerSU 's guide.

This guide from a community member Jorian might also be useful for you: http://barterdex.readthedocs.io/en/latest/

**Comment by BLenselink** [comment]
Satinder,

Thanks for your quick respons including the links for further information. I'll check it out later this week!

**Comment by satindergrewal** [comment]
No problem.
Closing this issue. Please reply to the same if still having any issue or just create a new one.

Regards
