### ISSUE TITLE
Auto Balance load (enhancement)

### ISSUE THREAD

**Issue by regnar1** [KomodoPlatform/BarterDEX#238]
It would be cool to have a way to scan for, or autoscan on startup, all wallets with balances and load them in electrum. I know there's more to it, just thinking what would happen if you have Bitcoin or Ether and there is a Bitcoin fork or Eth airdrop that happens and the new coin is supported later, it'd be a good way to know you have balances for these random coins so you can trade them instead of checking each balance, or manually adding after checking etherscan.

Just a thought.

**Comment by satindergrewal** [comment]
not sure I get the enhancement request.
in BarterDEX GUI, after login the portfolio screen shows the balance of any added coins.
there is manage coins option too, which auto-add/enable coins in that list.
if auto-enable is done for X coins, they are enabled right upon your login and with the minimal efforts, and you see the balance there.
Getting info on other airdropped coins from any XYZ project the only effective way as per the current `marketmaker` version 1 API set is to add that coin's info in the coins.json file and started/restarting the `marketmaker`. So, not sure what else purely from the GUI's perspective I can do.
This probably more like a `marketmaker` version 2 request. and for that the relevant place is this:
https://github.com/artemii235/etomic-swap/issues/

@cipig 
Please close this one if this answers is covers the concerns.
