### ISSUE TITLE
Impossible to add Ethereum

### ISSUE THREAD

**Issue by Nekojitasama** [KomodoPlatform/BarterDEX#247]
I tried to recover my Ethereum from the 1.0.6 rc version of Barterdex,
but I discovered another bug, this is now completely impossible to add Ethereum:

When you try with Ethereum native mode you get this:
![crappy barterdex bug ethereum native](https://user-images.githubusercontent.com/36922817/41156660-2b5887b8-6b23-11e8-8667-e23d21b5520b.jpg)

And when you try with electrum mode you get this:
![crappy barterdex bug ethereum electrum](https://user-images.githubusercontent.com/36922817/41156666-2ef17e66-6b23-11e8-8467-f62990a5656e.jpg)

**Comment by himu007** [comment]
Hello @Nekojitasama! I have just downloaded and ran the latest GUI release version 1.0.6 and it is working as intended. Please check if you downloaded from Chainmaker's repo or KomodoPlatform repo. Please Note: ETH/ERC20 swap in BarterDEX is still in development and being tested. Don't test with your main funding account. Create a new account and use low amount of funds for testing.

**Comment by Nekojitasama** [comment]
This is fixed, thanks.
So I can now see that the closed #214 is still here...................
This is boring. I will open another issue...
