### ISSUE TITLE
Hyphenation in passphrase field, dynamic prewiev for adress, and USD equiv - suggestions 

### ISSUE THREAD

**Issue by 1mk3r** [KomodoPlatform/BarterDEX#249]
Please add text hyphenation in passphrase entry field on the login screen. For example look at waves platform password recovery screen, it is very useful when your passphrase is very long.

Also please add dynamic generated preview for adress (kmd) (like in waves platform) with option show/hide, it is also very useful, when you mistakes typing text.

Also please add USD equivalent column for any coin balance in portfolio (similar to existing now "KMD Value" column) and for offering price in any order raw in orderbook on the trading screen. 
USD equivalent will be very useful because you will be no more need to calculate it by hands. 
And also add settings menu option which enables or disables showing USD equivalent in portfolio and orderbook. 
USD equivalent can be taken from coinmarketcap, or any similar source.
And please add option to choice any other fiat equivalent Value, like in electrum wallet.

And also please add buttons (or any other GUI elements) in portfolio coin raw or in settings menu which retrieves Private key from any coin. 
For now it can be done only with debug console by typing corresponding command. But GUI ability to retrieve a key will be useful, because any newbie user will fast understand that only he really controls private keys and can retrieve them even in offline.

**Comment by siulynot** [comment]
these developments are being worked in hyperdex, please take a look here: https://github.com/hyperdexapp/hyperdex/releases/tag/v0.1.0-alpha.8
