### ISSUE TITLE
AtomicDEX??

### ISSUE THREAD

**Issue by Henrietta1989** [KomodoPlatform/BarterDEX#25]
> Those users who are waiting for easy version of BarterDEX should wait for AtomicDEX release, which is a separate GUI specially designed by keeping the regular users in mind

How this AtomicDEX thing is easier than BarterDEX and could you release screenshots or other info about it?

Any rough time frame when it is out? I was planning to download BarterDEX soon but if AtomicDEX comes out soon enough, i might wait it.

Thanks for making Atomic Swaps easy to newbies.

**Comment by satindergrewal** [comment]
As stated
>It'll be communicated on all channels when it will be released.
