### ISSUE TITLE
Impossible to send Ethereum

### ISSUE THREAD

**Issue by Nekojitasama** [KomodoPlatform/BarterDEX#251]
The previous issue I submitted was closed but another bug prevent me to verify it.
Now we can add Ethereum, I try to send Ether and it doesen't work at all, like in the issue #214
We can see "Transaction sent successfully" but the transaction ID is always UNDEFINED 
and of course nothing happens. Please test it before close this one. Thanks.
![shitty software](https://user-images.githubusercontent.com/36922817/41567706-d935b8b0-7361-11e8-8753-8063aa65ade8.jpg)

**Comment by siulynot** [comment]
will let the team know, try the new release to see if it works.

**Comment by satindergrewal** [comment]
Tested in latest code. This needs fix as API changed for `eth_withdraw`.
Will update this issue soon once fix is pushed.

**Comment by satindergrewal** [comment]
Please test and close this issue if your issue is fixed.

**Comment by siulynot** [comment]
please test this release, ETH withdraw should be fixed
https://github.com/KomodoPlatform/BarterDEX/releases/tag/v1.1.0
