### ISSUE TITLE
Error making withdrawal transaction (ZEC)

### ISSUE THREAD

**Issue by gonzalezea** [KomodoPlatform/BarterDEX#258]
Every time I try to withdraw zec in Barterdex from a t1 to a t1 addr (external exchanger) error below arise. Using v1.1.0 is worst because it said "No electrum server found for zec" & didn't even show zec coin.

Running on Ubuntu 16.04

![2018-07-12 16_53_44-minerland ubuntu w running - oracle vm virtualbox](https://user-images.githubusercontent.com/8069435/42641667-8cb3a9a8-85e4-11e8-972a-05e8941a725d.jpg)

**Comment by siulynot** [comment]
ZEC implemented some changes on their chain that disrupted the way transactions are done. We are working on getting them implemented on barterdex. For. Now our recommendation is to pull the wif key of your address from agama wallet and import it to a native ZEC wallet.

**Comment by imylomylo** [comment]
@gonzalezea Here are instructions that may assist you with getting WIF key (never share it, c+p in public etc. this is your ZEC) https://komodoplatform.atlassian.net/wiki/spaces/KPSD/pages/447873027/How+to+retrieve+WIF+key+of+your+BarterDEX+seed+using+Agama+wallet

Hope this helps!

**Comment by gonzalezea** [comment]
Thx guys !!, using above procedure I managed to get funds to a full node ZEC wallet. Hope next-gen BarterDEX make this easier (or unnecessary) for all of us.

**Comment by cipig** [comment]
marketmaker now supports sapling
Please update to latest BarterDEX (dev branch) and also update your local coin database and try again
ZEC now needs the additional paramater "txversion:4": https://github.com/jl777/coins/blob/master/coins#L2656
