### ISSUE TITLE
bug: only 3 coins in dashboard

### ISSUE THREAD

**Issue by 1mk3r** [KomodoPlatform/BarterDEX#261]
Barterdex 1.1.0 linux 64 tar.gz (i use linux mint xfce 18.3-64bit), there are only 3 coins in dashboard - kmd-btc-etomic, and no more. In a trading panel same situation. Similar problem at windows (i use Win7-64) - a lot of empty rows in selection menu at the dashboard, and there are no way to choose any coin.
Barterdex 1.0.7 works fine, but there are no orders in orderbooks.

**Comment by himu007** [comment]
Hello @1mk3r. From BarterDEX GUI version 1.1.0 we have a new feature called Manage Coins which uses https://github.com/jl777/coins repo to get coin list, icons and explorer data.

Please follow this updated guide to add coins in BarterDEX GUI https://komodoplatform.atlassian.net/wiki/spaces/KPSD/pages/441483271/How+to+add+coins+assets+tokens+to+BarterDEX+GUI+for+trading

Also, this YouTube video shows how to do it easily (also available via the above link) - https://www.youtube.com/watch?time_continue=1&v=zVziQQvjb-I

**Comment by 1mk3r** [comment]
Is there no way to implement this feature to work from box (like it was), because now it is not a user-friendly way? For example, it will be not useful from linux liveusb, because it will demand to execute your instruction for each coin, each time.

**Comment by imylomylo** [comment]
Interesting comment about the liveusb use-case.  Thanks for raising the issue.

Yes this is a new "problem" we are happy you raised about needing to configure it vs out-of-the-box working.

We will raise it with the developer for some workarounds.
