### ISSUE TITLE
[macos]] GUI version seems not complete

### ISSUE THREAD

**Issue by brrrrrr** [KomodoPlatform/BarterDEX#267]
I get errors like 'can't find electrum server' and coin icons are missing. It start's up, but asicly all actions end in error. Last working GUI version for mac seems to be 1.0.7-rc.
<img width="446" alt="screen shot 2018-09-16 at 17 53 16" src="https://user-images.githubusercontent.com/29727866/45598399-c5a98e00-b9db-11e8-998d-cae81b4f6ca8.png">
<img width="224" alt="screen shot 2018-09-16 at 17 48 37" src="https://user-images.githubusercontent.com/29727866/45598400-c6dabb00-b9db-11e8-9c2f-10fba9ca3b33.png">
<img width="185" alt="screen shot 2018-09-16 at 17 48 22" src="https://user-images.githubusercontent.com/29727866/45598401-c8a47e80-b9db-11e8-8fe6-ddb8212ad9da.png">

**Comment by brrrrrr** [comment]
Same with checkout latest dev branch
<img width="468" alt="screen shot 2018-09-17 at 11 00 05" src="https://user-images.githubusercontent.com/29727866/45614272-3fd42400-ba69-11e8-95d2-2053e087675b.png">
<img width="412" alt="screen shot 2018-09-17 at 11 00 31" src="https://user-images.githubusercontent.com/29727866/45614273-419de780-ba69-11e8-9435-76d571d9102e.png">


errors while installing
`/Users/bartvm/BarterDEX/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, mkdir '/Users/bartvm/BarterDEX/node_modules/electron/electron-tmp-download-23078-1537174607632'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@2.0.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@2.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

errors while starting:

`start prices_loop
>>>>>>>>>> DEX stats 127.0.0.1:7783 bind sock.24 DEX stats API enabled at unixtime.1537174776 <<<<<<<<<
sig failure.({"pubkey":"f20555287c8b9bb3889a69c69e457e8734a9e4cee45b84c30ee058ea6424c333","base":"KMD","rel":"BTC","price":0.0001
open
{ Error: ENOENT: no such file or directory, open '/Users/bartvm/Library/Application Support/BarterDEX/CoinsDB/explorers/KMD'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/bartvm/Library/Application Support/BarterDEX/CoinsDB/explorers/KMD' }
{ Error: ENOENT: no such file or directory, open '/Users/bartvm/Library/Application Support/BarterDEX/CoinsDB/electrums/KMD'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/bartvm/Library/Application Support/BarterDEX/CoinsDB/electrums/KMD' }
{ Error: ENOENT: no such file or directory, open '/Users/bartvm/Library/Application Support/BarterDEX/CoinsDB/explorers/KMD'`

**Comment by cipig** [comment]
you need to first enable all the coins in manage coins tab: https://www.youtube.com/watch?v=zVziQQvjb-I

**Comment by brrrrrr** [comment]
Okay. Updated coins (local) and seems solved. Only 'my offers' (not updating) and 'trade status' (sluggish) remain to be problems
