### ISSUE TITLE
Tried to send BUCK to BarterDEX, but did not see it in the software

### ISSUE THREAD

**Issue by gucky25** [KomodoPlatform/BarterDEX#269]
Dear reader,

I tried to send BUCK to BarterDEX 1.1.2-rc, but even after more than 100 confirmations, I could not see it in the software.
After restarting the software I did not get the same receive address for BUCK.
See attached screenshots.

Can I correct this in any way?

Thanks in advance,
Edwin van Hierden

![2018-10-30 16_29_46-barterdex - 1 1 2-rc](https://user-images.githubusercontent.com/8337541/47729857-3ee60300-dc61-11e8-9278-3ec302067aa8.png)
![2018-10-30 16_28_11-buck](https://user-images.githubusercontent.com/8337541/47729858-3f7e9980-dc61-11e8-8a37-91bf7754c1e5.png)
![2018-10-30 16_27_51-buck](https://user-images.githubusercontent.com/8337541/47729859-3f7e9980-dc61-11e8-96a0-e72243fd9f15.png)
![2018-10-30 16_27_22-buck](https://user-images.githubusercontent.com/8337541/47729861-3f7e9980-dc61-11e8-903e-b9e396d2cc89.png)

**Comment by cipig** [comment]
Diffent addresses mean different passphrases were used. Make sure you input the exact same passphrase at login (no leading or trailing spaces).

**Comment by gucky25** [comment]
Thanks for the response. Tried several times, but when I do this, my receive address is everytime different after adding the BUCK coin. Probably I used the wrong passphrase, but can't find the correct combination. Is there a way to recover the BUCK coins on this address: t1WKfvwkLu9LYD1YD7dMnUUmb5QPe9VVMMp ?

**Comment by cipig** [comment]
The only way to "recover" coins is to know the passphrase or the private key (which is derived from the passphrase). I assume you are doing cut&paste of the passphrase... take care that no whitespaces are added to the end of the passphrase, this happens all the time in windblows, as i heard.

**Comment by gucky25** [comment]
Thanks. I get it. Can't get it correct, so now there are some lost BUCK coins.
