### ISSUE TITLE
Can't do an operation with Aywa

### ISSUE THREAD

**Issue by GetAywa** [KomodoPlatform/BarterDEX#272]
Hi! Thank you for added coin in a shot time! We can't do any operations yet. The coin added as Native, wallet is stared. 
when trying to set a buy or sell order, getting this error at console:
{ Error: ENOENT: no such file or directory, open '/Users/user/Library/Application Support/BarterDEX/CoinsDB/electrums/AYWA'
Using macOS, Ubuntu.
Thanks in advance!

**Comment by cipig** [comment]
There are no electrums configured for AYWA, that is the error message. Has nothing to do with native.
Make sure your aywa.conf contains at least this entries:
```
server=1
rpcuser=xxxx
rpcpassword=xxxx
```
and the wallet listens to the rpcport configured (2778). BarterDEX must be able to connect to the rpcport of the wallet by using the credentials from aywa.conf.

**Comment by GetAywa** [comment]
Hi!
We can use BarterDEX, it’s working in electrum mode. Thank you!

Our ElectrumX servers are working well too.

Please check it:
electrum1.getaywa.org <http://electrum1.getaywa.org/> (TCP_PORT=50001, SSL_PORT=50002)
electrum2.getaywa.org <http://electrum2.getaywa.org/> (TCP_PORT=50001, SSL_PORT=50002)


Thank you!
NiconX
