### ISSUE TITLE
BarterDEX cant find electrum servers Error on all coins

### ISSUE THREAD

**Issue by akshaynexus** [KomodoPlatform/BarterDEX#274]
This happens on macOS.
<img width="466" alt="screen shot 2019-01-12 at 9 19 59 am" src="https://user-images.githubusercontent.com/25401217/51070005-42c3d780-164b-11e9-9e5d-2510f1feea8f.png">

**Comment by cipig** [comment]
Electrums are working fine. Please update your local coin database.
