### ISSUE TITLE
Coins added to portfolio are not saved across restarts

### ISSUE THREAD

**Issue by webworker01** [KomodoPlatform/BarterDEX#29]
Is there a setting to make this save?

**Comment by prioritylabs** [comment]
this is a very serious issue, I had mini heart attack thinking my funds dissapeared :)

**Comment by satindergrewal** [comment]
Not serious issue, but a good feature to have once core functionalities are sorted out to solid, which we are reaching already. Such fancy features and more will come soon to BarterDEX.

Feel free to add more ideas, feature requests in issues.

**Comment by adhoc115** [comment]
I must admit this is not really an enhancement or feature, it is essentially! Without it, testing cost me hours to always add the same type of wallets. In 2018 if you type some sort of pw or phrase you expect that your account remember your actions. Imagine how Coinomi would look like if they would say well, Coins are save but you have to add every time you want to look up. Could be a job full time these days ;9

There is one more point I would like to add. In Dashboard there is the column “Price”. I wasn’t able to trade so far. But what the hell is “Price”. It would be nice to add a unit.
“Force” 4

**Comment by regnar1** [comment]
"In Dashboard there is the column “Price”. I wasn’t able to trade so far. But what the hell is “Price”. It would be nice to add a unit."

I believe price is "priced" in KMD. meaning the unit you see is its value in KMD. If you load KMD coins it shows price at 1, which is why I think this. Though Pricing would probably make more sense in btc or fiat as many peoples portfolios are valuations of this. I get why they want to use KMD, I just hodl Komodo and never really sell it...

**Comment by webworker01** [comment]
The time mathing out conversion of value from KMD <-> BTC is minimal, but an option to display portfolio value how we want would not be unwelcome.

Having to recreate the portfolio every time we start the app up is tedious and repetitive and is the main issue I have raised.  One does not require the other.

**Comment by satindergrewal** [comment]
Added to latest commit: https://github.com/KomodoPlatform/BarterDEX/commit/b41700044e2c91aa10434174c8307b142dc80f24
<img width="1792" alt="screen shot 2018-03-11 at 9 22 59 am" src="https://user-images.githubusercontent.com/12998093/37246528-6a175cd6-250f-11e8-85f6-aaf9c1cf31ba.png">
<img width="1792" alt="screen shot 2018-03-11 at 9 32 19 am" src="https://user-images.githubusercontent.com/12998093/37246531-7d092b80-250f-11e8-9c6c-fa5eb4bee232.png">

**Comment by webworker01** [comment]
This is the best day :D
