### ISSUE TITLE
where to view past trades by other traders?

### ISSUE THREAD

**Issue by prioritylabs** [KomodoPlatform/BarterDEX#31]
cant see previous trades, only current orderbook avaliable

**Comment by satindergrewal** [comment]
You have to keep your BarterDEX running to always have the latest and old dataset of the network. The dataset is accessible in real-time, and as long as your BarterDEX is running, you keep getting all updates. Once closed, you are not getting the data in between that time you were offline.

**Comment by prioritylabs** [comment]
@satindergrewal  Ok I keep it open, where I can get the history though while it open?

Also there is a website for "offline" charts
http://dexcharts.com
maybe there is a website for past trades?
