### ISSUE TITLE
Trade details are inaccurate

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/BarterDEX#32]
Trade details assume that the entire UTXO is part of the trade.

![example trade](https://user-images.githubusercontent.com/21057518/34529043-579981fc-f070-11e7-9978-7758691c6bb9.JPG)
The "Price paid in CoinX" (highlighted) is the actual total (**including** fee) 

`{ "expiration": 1515005428, "tradeid": 3208818687, "requestid": 3447512412, "quoteid": 3138046698, "iambob": 0, "Bgui": "", "Agui": "simplegui", "gui": "simplegui", "bob": "KMD", "srcamount": 4.3296201, "bobtxfee": 0.0001, "alice": "DGB", "destamount": 686, "alicetxfee": 0.001, "aliceid": "287573898672013313", "sentflags": [ "alicespend", "bobspend", "bobpayment", "alicepayment", "bobdeposit", "myfee", "bobrefund" ], "values": [ 4.3297201, 686.00099999, 4.3298201, 686.002, 4.87102261, 0, 0.88288288, 4.87092261, 0, 0, 0 ], "result": "success", "status": "finished", "finishtime": 1514989874, "bobdeposit": "7141dd57e5ddf00da3e9d4b4831041b497fa25a6e1c905f56da1045e7f45c62b", "alicepayment": "000b57edf9f403ec5bc31b46c838ce2f91924bf45c9cdee9a1375bbbfdc1f26c", "bobpayment": "804a3632f72c591025504accaee329f8fa009bd04a8b550aa7149d08bbdeb41c", "paymentspent": "0000000000000000000000000000000000000000000000000000000000000000", "Apaymentspent": "3987b192a0d7382d41097c87dea69a53b07ed197d1c48a43a2f7b681f9cc8e6f", "depositspent": "9343b524196aee97aaeaa06934f4907886a3217ccf4a620ed74ffab0f25ec7c4", "method": "tradestatus" }`

The remainder of the UTXO is accually returned to the user as change (as expected).
https://digiexplorer.info/tx/000b57edf9f403ec5bc31b46c838ce2f91924bf45c9cdee9a1375bbbfdc1f26c

**Comment by siulynot** [comment]
Is this something that still happens?
