### ISSUE TITLE
win: buy order not matched with sell order

### ISSUE THREAD

**Issue by prioritylabs** [KomodoPlatform/BarterDEX#34]
check screenshot, I have open buy order for 0.1 SN for 22.99xx. I placed it few hours ago
now new sell order appeared which is lower than my price.

how is that possible?

![image](https://user-images.githubusercontent.com/26009915/34530027-e70d0fea-f0be-11e7-967c-e56f803c7e40.png)

**Comment by prioritylabs** [comment]
I also cannot "buy market" effectively, see screenshots - why system didn't bought 0.2 SN for me?

step1
![image](https://user-images.githubusercontent.com/26009915/34530527-7a90f5dc-f0c0-11e7-8c1b-bb038676e404.png)
step2
![image](https://user-images.githubusercontent.com/26009915/34530537-83913156-f0c0-11e7-9aa3-6948d2108039.png)
and yet after the step 2 I repeat step1 for the same result

**Comment by satindergrewal** [comment]
you are trying to think and expect DEX to work as Centralised Exchange. Please talk this issue with others in #tradebots channel of SuperNET slack to get a better understanding.
