### ISSUE TITLE
Please provide instructions on recovering funds to another wallet

### ISSUE THREAD

**Issue by darijanzg** [KomodoPlatform/BarterDEX#35]
I installed BarterDEX yesterday, added some BCH to it, exited and after I came back to BartedDEX the funds show 0 BCH.
However, checking on the blockchain, funds are still on that address.
Recovering to BCH with the 12 words seed I got from Barter DEX during initial installation did not work.
Here is my log file, just in case.
[logFile.log](https://github.com/KomodoPlatform/BarterDEX/files/1602780/logFile.log)

Thank you, in advance, for your help.
[logFile.log](https://github.com/KomodoPlatform/BarterDEX/files/1602777/logFile.log)

**Comment by satindergrewal** [comment]
Please get help from other testers in #tradebots channel of Komodo Platform Slack:
https://www.komodoplatform.com/en/slack-invite
