### ISSUE TITLE
[Interface] Show all currently open orders

### ISSUE THREAD

**Issue by kjpeee** [KomodoPlatform/BarterDEX#40]
I placed order for CRW buy 
I can see my order for CRW in yellow
![image](https://user-images.githubusercontent.com/26009915/34619231-90c054ae-f252-11e7-9035-99f6c4acfa87.png)

Then I switched to the other coin and cant find my open orders anywhere (including my prices / trade status - not sure if these values should appear there though)

![image](https://user-images.githubusercontent.com/26009915/34619250-a1ee0ae6-f252-11e7-8729-1dcf296cd707.png)

**Comment by satindergrewal** [comment]
My Prices tab should show you your all active offers. It refreshes I think every minute. So, in case you didn't see the latest updates possibility is you saw it before it refreshing those and listing the updated offers list on My prices tab.

If that's the case, hit the refresh button on My Prices tab and it should show the price offers of all coin pairs there.

Also, when you change the second pair coin in Trading Pair tab, the screen starts showing the `orderlist` of that pair. The previous pair `orderlist` won't show on the new selected pair.

Hope this clears.
