### ISSUE TITLE
ReadMe.md needs update

### ISSUE THREAD

**Issue by finddabug** [KomodoPlatform/BarterDEX#41]
Hi folks,
the install instructions on the `Readme.md` file need to be updated. For example in the Electron section `For end users` the command: `sudo npm install electron-prebuilt -g` is outdated and gives an error when using. The usage of an Electron server is not reflected anywhere but I think users would prefer it as the standard. E.g. update the `Instructions to test` section.

**Comment by satindergrewal** [comment]
>The usage of an Electron server is not reflected anywhere

 - The Desktop framework users use in all platforms (Winblows, Linux, MacOS), all use Electron.
 - It is not Electron Server.
 - Updated ReadMe with electron command. Thanks!
