### ISSUE TITLE
portfolio Dissapperared

### ISSUE THREAD

**Issue by mauricekomo** [KomodoPlatform/BarterDEX#42]
Hello

Today signed up for barterdex with my phrase. I transferred Hush and Komodo into the exchange. i got all the confirmation and credit of Hush into my portfolio. After few hours i tried to login with my phrase but i see my portfolio empty with no coins. Please help me to rectify this. thanks

**Comment by mauricekomo** [comment]
I see the address has been changed to receive funds in my account. The passphrase is correct and there is nothing wrong with it. can anyone help to rectify this?

**Comment by satindergrewal** [comment]
I no way it is possible that the same passphrase is giving you the different set of addresses. Please check and verify you are using the correct passphrase. If you don't have the correct passphrase that you used the first time nobody can help you.
