### ISSUE TITLE
Coin never shows up in wallet

### ISSUE THREAD

**Issue by cryptcurr1** [KomodoPlatform/BarterDEX#43]
I tried depositing hush from my wallet into the BarterDEX wallet using the receive address it gave me. The transaction has been confirmed numerous times. Nothing has shown up in BarterDEX, balance still reads as 0. Restarting BarterDEX removes Hush from the portfolio and it has to be added again. Is there a minimum for the balance not to read zero? I send .001 Hush

**Comment by CryptoXman79** [comment]
I had the same story with ZCL and Desire....
Sent coins but after so much confirmations, I can't see anything in balance!
Isn't it an electrum security issue consequence?

**Comment by cipig** [comment]
There are no electrum servers for ZCL and Desire. ZCL is in the making, Desire is not supported. In order to use this coins, you will have to install the wallets. Regarding the security issue: We are not affected by this, it is an issue of the electrum client, which we don't use.

**Comment by satindergrewal** [comment]
If the Electrum mode doesn't show balance I can only guess few things:
- Electrum server(s) it is connected to is not up to date with the blockchain and isn't giving correct info
- There is some communication error or timeouts (maybe) which is not updating the balance from Electrum servers. That can be possible in cases of slow internet connection.

If the selected coin is not activating in Electrum mode, then most certainly it doesn't have the Electrum support added yet. For that, you can contact @cipig. He manages some Electrum servers for BarterDEX coins.

The alternate solution you can try is just installing the native coins of the coin, setup them properly with the RPC settings, and add them in `Native Mode` in BarterDEX.

Hope this helps.
