### ISSUE TITLE
None of these coins are available to swap.

### ISSUE THREAD

**Issue by robjiz** [KomodoPlatform/BarterDEX#45]
OctoCoin
ArcticCoin
BridgeCoin
Bata
BitDeal
Bitcore
BitcoinZ
BitSend
BlockNET
CreativeCoin
Desire
e-Gulden
EuropeCoin
Florincoin
GameCredits
GoByte
GlobalToken
HunterCoin
I0Coin
InternetofPeople
Innova
LBRY Credits
MachineCoin
MAGACoin
MonetaryUnit
MoonCoin
Myriad
NavCoin
Pura
Pivx
Qtum
RevolverCoin
SexCoin
Stratis
SmartCoin
Straks
SysCoin
TerraCoin
Unitus
ZCoin
ZClassic
Zero
ZetaCoin

**Comment by cipig** [comment]
None of these coins have electrum support, so in order to trade them, you will have to install and sync the respective wallets first.

**Comment by robjiz** [comment]
Ahhh, okay, thank you!
