### ISSUE TITLE
Making a wallet communicate with Barterdex.

### ISSUE THREAD

**Issue by CryptoXman79** [KomodoPlatform/BarterDEX#46]
Hi,

How can I make my wallet communicate with Barterdex?
I think that Barterdex cannot have access to the blockchain of my wallet, that's why I cannot see balance in Barterdex even if I can see it in the coin explorer.
Thank you.

**Comment by satindergrewal** [comment]
Are you trying to enable `Native Mode` for a coin and unable to connect to it?
- Make sure it's RPC settings are correct. RPC settings of a coin (example BTC's bitcoin.conf):

```shell
rpcuser=change_this_username
rpcpassword=change_this_password
txindex=1
server=1
rpcbind=127.0.0.1
bind=127.0.0.1
```

- Make sure that coin is synced

Then try again enabling `Native Mode` for that coin.

If still issue, then better get help on Komodo Platform Slack channel #tradebots

**Comment by CryptoXman79** [comment]
I did but still no luck balance doesn't show...
That's a big problem ! We do not have our privkeys from Barterdex, so my coins are locked !!!

**Comment by CryptoXman79** [comment]
Should I open a port in my firewall ?

**Comment by satindergrewal** [comment]
best is to get help from live chat. Please join Komodo Platform slack and get help in #tradebots channel.

**Comment by CryptoXman79** [comment]
Can I have invite for Slack channel please ?

**Comment by adhoc115** [comment]
I have the same issue; I tried to set up a connection all day to Desire Wallet and Arctic-Coin Wallet. I made the the changes in *.conf of wallets like 

rpcuser=change_this_username
rpcpassword=change_this_password
txindex=1
server=1
rpcbind=127.0.0.1
rpcport=currency port

Except of bind=127.0.0.1. that causes an error in the wallet in my case. 

I'm able to connect to a Desire/Arctic-Wallet. But there is no balance seen by BarterDEX.
I send 0.01 Desire to the Receive-Wallet which is shown by hitting the button. There was no income after couple of confirmations. So what’s Tic, Tric & Trac about this cute guy and witch part is generating the Wallet-Address for that Native-Wallet connection anyway, Barterdex or the RPCServer?

To be honest a belief you guys could change the nature of money with your experiment, I’m very reverent of your work! Go ahead and let’s (ex)change to the better

**Comment by cipig** [comment]
this are steps i have done to install DSR and ARC and it is working great
`git clone https://github.com/lazyboozer/Desire
cd Desire
chmod 755 autogen.sh share/genbuild.sh
./autogen.sh
./configure --with-incompatible-bdb --with-gui=no --disable-tests --disable-bench --without-miniupnpc --disable-zmq
make -j4
sudo make install
sudo strip /usr/local/bin/desire*
mkdir ~/.desirecore
echo "server=1" >> ~/.desirecore/desire.conf
echo "txindex=1" >> ~/.desirecore/desire.conf
echo "listen=0" >> ~/.desirecore/desire.conf
echo "rpcuser=barterdsr" >> ~/.desirecore/desire.conf
echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >> ~/.desirecore/desire.conf
chmod 0600 ~/.desirecore/desire.conf
desired -daemon

git clone https://github.com/ArcticCore/arcticcoin
cd arcticcoin
./autogen.sh
./configure --with-incompatible-bdb --with-gui=no --disable-tests --disable-bench --without-miniupnpc --disable-zmq
make -j4
sudo make install
mkdir ~/.arcticcore
echo "server=1" >> ~/.arcticcore/arcticcoin.conf
echo "litemode=1" >> ~/.arcticcore/arcticcoin.conf
echo "listen=0" >> ~/.arcticcore/arcticcoin.conf
echo "rpcuser=barterarc" >> ~/.arcticcore/arcticcoin.conf
echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >> ~/.arcticcore/arcticcoin.conf
chmod 0600 ~/.arcticcore/arcticcoin.conf
arcticcoind -daemon`

You will have to make sure that the wallets use the default directory for the blockchain and the default rpcport... and that they are indeed listening to that port.
