### ISSUE TITLE
Windows 8.3 rc does not open gui

### ISSUE THREAD

**Issue by passcombo** [KomodoPlatform/BarterDEX#47]
After clicking BarderDEX.exe gui does not open. The app works however in the background (task manager).

It also worked a couple of times in the beggining, but only first run after windows 10 boot/restart. Needed to restart after closing dex, as the 2nd run after closing dex did not open gui (just background task visible in task manager). Then after some time the problem become persistent - even after the restart Barterdex gui does not load.

**Comment by satindergrewal** [comment]
next time when it does not load, please try removing settings.json file from it's data directory, then try restarting it and let me know if the results.

**Comment by satindergrewal** [comment]
please reply to this issue again or open a new issue if this issue still exists. try the troubleshooting steps suggested.
