### ISSUE TITLE
Show error/message if Electrum server is not available for a coin

### ISSUE THREAD

**Issue by ahilis** [KomodoPlatform/BarterDEX#48]
Can't add coins: ZCL, BTCH in electrum mode. Portfolio coins window refreshes but there is no selected coin.
For example: BTC, ZEC, HUSH works good

**Comment by cipig** [comment]
Deployed electrum servers for BTCH and ZCL and added them to BarterDEX.

**Comment by ahilis** [comment]
Which one is the newest? The only version I can see in releases is 0.8.3-rc

**Comment by finddabug** [comment]
Would also be nice if there is a pop-up error displayed that there is no Electrum server available for a certain coin e.g. the PURA coin.

**Comment by ahilis** [comment]
0.8.4-rc - BTCH and ZCL works good. Thank you!

**Comment by cipig** [comment]
This is implemented now, as i saw in the newest version
