### ISSUE TITLE
Barterdex install on win 10

### ISSUE THREAD

**Issue by mitchvac** [KomodoPlatform/BarterDEX#49]
issue with two files after the install 
node.dll and ffmpeg.dll even when runnning is admin mode

during install blue window pop-up 

i clicked more info **install anyway**

still did not work 

Antiv =windows defender

**Comment by satindergrewal** [comment]
you are double clicking on BarterDEX.exe in a zip file.
extract it and then try.

**Comment by mitchvac** [comment]
this is your response , did you fix anything , I did that 4 times same
result

**Comment by N8Solutions** [comment]
Are you sure you have extracted the full contents of the zip file and are
running the BarterDEX.exe from the extracted folder? I'm running it on Win
10 with absolutely no problems.

**Comment by mitchvac** [comment]
Can you send me a video of your system indicating it’s windows 10’home
addition and show me the program up and running

301-532-9100 this is my cell you can send to me via your smartphone
