### ISSUE TITLE
Barterdex seems to STEAL coins with watchonly addresses !

### ISSUE THREAD

**Issue by CryptoXman79** [KomodoPlatform/BarterDEX#52]
Hush + swingwallet.
Barterdex send funds by creating watchonly addresses wich you don't own private keys...Who own these keys? That seems to stink far away...
BE VERY CAREFULL !!! After watching blockexplorer, I can say it is a robbery...more than 10000 Hush have transited in this address....This IS NOT a bug ! but a HACK !

Here is the address: t1Y9ukZMkNAYonCFVp3jSdx7NT8dEsXss7k

**Comment by n41r0j** [comment]
What are you trying to do. Spread FUD? There are good reasons for using watch-only addresses. 

What's up with that address? Why is sending and receiving 10000 HUSH a robbery?
