### ISSUE TITLE
Barterdex extremely slow/non responsive

### ISSUE THREAD

**Issue by crypt2kpr** [KomodoPlatform/BarterDEX#57]
anyone experiencing issues with barterdex? i can get to my dashboard but when i click "exchange" for a coin to bring me to the trading interface, nothing happens . running windows 10 if that helps. thanks!

**Comment by JukioKe** [comment]
I have experiencing same kind of issues. Running version 0.8.4-rc with Win10 and almost everything is loading so slowly that's it's almost unusable.

**Comment by crypt2kpr** [comment]
have  i been accepted into slack?. the issue is still ongoing and i cant do
anything beyond view my dashboard

**Comment by crypt2kpr** [comment]
Can you please approve my slack invite. i asked @barterdex on twitter for
help also. working the system on windows 10 is extremely slow...im trying
to swap KMD for HUSH but nohthing happening. please help

**Comment by satindergrewal** [comment]
if you are using Windows, better switch to Native Mode for coin(s)
