### ISSUE TITLE
Cant install Bartedex

### ISSUE THREAD

**Issue by henasau** [KomodoPlatform/BarterDEX#58]
I am trying to open Bartedex ver 0.8.4-rc in Windows 7 but it locks up on "Starting Barterdex. Please Wait" screen for ever.

**Comment by cryptatometrader44** [comment]
Can i ask to you where and how you install bertdex on windows. I don't understand the readme page of this project.
Where is the setup ??? 

I'm not sure I understand, and I feel like to do yourself setup for Linux?
Do I understand well ??? I have to compile myself the setup ???? But why not directly propose a setup for windows ?? I do not really understand why it is so complicated to install this software that I think it is very promising.

**Comment by henasau** [comment]
On github there is BarterDEX-win64-x64-0.8.4-rc.zip file. Which I unzipped and run BarterDEX.exe file. There is no installation involved. I followed this guy on youtube       https://youtu.be/drl4FEuEoBY

**Comment by cryptatometrader44** [comment]
Ok, i've seen on your vidéo after my post .

Thanks.

**Comment by satindergrewal** [comment]
Try installing Agama Wallet first which installs the same dependencies required by BarterDEX if you are stuck on just starting of the BarterDEX screen.
