### ISSUE TITLE
Buyer/Sellers auto-fill doesn't function properly

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/BarterDEX#6]
clicking `A` should have the same effect on the items in yellow as clicking `B`
and
clicking `C` should have the same effect on the items in yellow as clicking `D`
(given that clicking either `A` or `C` auto-fill both `E` and `F`)

![40](https://user-images.githubusercontent.com/21057518/34028406-78dacda0-e128-11e7-9f34-d08a0c437ad6.jpg)

**Comment by TheComputerGenie** [comment]
Expected:
When user clicks on `A` (or any other bid in the list) they should expect that when the GUI does the auto-fill of `E` and `F` that they are selling to that user (or at that price, anyway).
Using the image as a reference, the words in the yellow area would say "SELL" (as they do in the image) and clicking the button will place a sell order.

When user clicks on `C` (or any other ask in the list) they should expect that when the GUI does the auto-fill of `E` and `F` that they are buying from that user (or at that price, anyway).
Using the image as a reference, the words in the yellow area would say "BUY" and clicking the button will place a buy order.


Actual:
Using the image as a reference, the words in the yellow area that say "SELL" do not change state when a orderbook item is clicked and the user must manually click `D` or `B` to match their intentions before placing their order.

**Comment by jansako** [comment]
How about: 'buy/sell does not auto-switch when clicking on different order types'.

**Comment by jansako** [comment]
Playing the devil's advocate, what if I want to 'underbid' the existing lowest sell or overbid the highest buy? In that case I do not actually want the buy/sell to switch... :-)

**Comment by satindergrewal** [comment]
reading the explanation felt conflicting with last `Actual:` explanation part.

Anyway, I implemented auto select BUY/SELL option based on the `orderbook` list click.

Let me know if that solves what you asked for.
