### ISSUE TITLE
KMD balance is not updated (electrum mode)

### ISSUE THREAD

**Issue by goldenman-kmd** [KomodoPlatform/BarterDEX#60]
![balacekmd](https://user-images.githubusercontent.com/33863358/34947902-e27ef3a0-fa4e-11e7-9b5c-f722df17c880.png)

Mode : Electrum mode
Version : 0.8.4
OS: windows 10 64bit
Problem : My KMD balance is not updated since 2 days ago.
I made several transactions after 153 KMD but BarterDEX still show old balance.
I have 83 KMD in blockchain, but BarterDEX show 153 KMD.

https://www.kmd.host/address/RSXqt8TGcPZEreb8us4KBiREM5JbUk6Ffh

**Comment by cipig** [comment]
4 out of 6 KMD electrum-servers were out of sync because of this issue in electrum-server
https://github.com/kyuupichan/electrumx/issues/185
Had to restart them, you should now see your correct balance.
