### ISSUE TITLE
Missing dependancy libcurl-gnutls on Manjaro Linux

### ISSUE THREAD

**Issue by ericvrp** [KomodoPlatform/BarterDEX#61]
I first got this message.

`/home/eric/Github/BarterDEX/assets/bin/linux64/marketmaker: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory`

After installing libcurl-gnutls BarterDEX started is expected.

**Comment by siulynot** [comment]
solution found by user.
