### ISSUE TITLE
Can't trade with KMD even though i have some coins in my balance

### ISSUE THREAD

**Issue by breathespace** [KomodoPlatform/BarterDEX#63]
![issue barterdex](https://user-images.githubusercontent.com/35494845/34994275-427123a8-fad3-11e7-8ea0-60f271086e25.jpeg)

Hi, 

I have an issue with the trading option. I transferred some KMD from Cryptopia to my BarterDEX-address. The balance shows, that I own 56.18192095 KMD-Coins. If I now want to buy some HUSH, for example 32 with a maximum price to buy set at 1,75 KMD, which equals 56 KMD, a pop-up appears on the upper-right corner: "Trade Info. Can't find a deposit that is close enough in size. Make another deposit that is just a bit larger than what you want to trade". A second pop-up gives me the advice to transfer some KMD to my deposit address. Even if I try to buy only 1 HUSH it says the same... what am I doing wrong? Or is there some bug?

**Comment by breathespace** [comment]
No it shows me, that i have none left! I have searched for my deposit address in the blockchain explorer and found, that i have a balance of 56.... but i can´t find them on BarterDEX. 1 hour ago I saw them. What is happening? If I look up the recent trades, i cant find any history (quite different 1 hour ago)...

**Comment by satindergrewal** [comment]
not a bug at all.
BarterDEX is NOT balance based. it's UTXO based.

Please get in contact with the other members in Komodo Platform Slack to get to know and understand these basic concepts. The helpdesk and knowledge base articles are being updated with guides to get users started. Until those gets available, it's best to get help from users in #tradebots channel in Komodo Platfrom Slack.
