### ISSUE TITLE
BarterDex V 0.8.4 doesn't start

### ISSUE THREAD

**Issue by jose621989** [KomodoPlatform/BarterDEX#68]
I downloaded the latest version of BarterDex and it has been in Starting BarterDex mode for two hours now. Should I be concerned about that? Does it normally take this long? Please assist thank you.

**Comment by satindergrewal** [comment]
If you are on Windows, follow these troubleshooting instructions:
https://github.com/KomodoPlatform/BarterDEX#troubleshooting

If you still get the same issue, describe your OS and version details.

**Comment by jose621989** [comment]
In uninstalled and installed it still having the same issues. I have a Windows computers with all the specifications required to use barterdex so not sure why it's not working.

Let me know what my next steps should be thank you



Sent from my Sprint Samsung Galaxy S8+.


-------- Original message --------

**Comment by passcombo** [comment]
I have same with bDEX 8.8. UI not loading. I have the Visual C++ installed.

**Comment by siulynot** [comment]
Is this still an issue in the latest versions?

**Comment by jose621989** [comment]
Hey,

Thank you for reaching out. Honestly, I have not had the chance to re-install the new version. I will give it a shot and hope that it will work without any issues.

I'll keep you all posted.

Thanks!

Jose
________________________________

**Comment by siulynot** [comment]
New version fixed issue.
