### ISSUE TITLE
Windows v0.8.4-rc antivirus alert

### ISSUE THREAD

**Issue by alespuh** [KomodoPlatform/BarterDEX#69]
When logging in and choosing where to login resources/app/assets/bin/win64/marketmaker.exe gets flagged as malicious by AVG and moves to quarantine.

**Comment by satindergrewal** [comment]
then add it to whitelist. Or if you still fill suspicious, compile it yourself, and replace the file. Can use this repo to compile it yourself:
https://github.com/jl777/SuperNET
