### ISSUE TITLE
"auto-repeat" always enabled

### ISSUE THREAD

**Issue by goldenman-kmd** [KomodoPlatform/BarterDEX#7]
Even I never checked " Enable auto-repeat this trade" checkbox, BarterDEX repeat trade automatically.

Uncheck after check it, still repeat trade automatically.

**Comment by satindergrewal** [comment]
<img width="1792" alt="screen shot 2017-12-20 at 3 04 04 pm" src="https://user-images.githubusercontent.com/12998093/34187624-4202bafe-e597-11e7-821e-7b5c0eaea374.png">

I need information like what it's showing in the screen shot.
based on my test I couldn't replicate the issue.

**Comment by goldenman-kmd** [comment]
![image](https://user-images.githubusercontent.com/33863358/34219590-0571a95c-e5f5-11e7-8dea-11d1ffd7b683.png)

according to screenshot,
1) I made BUY 0.0255 MNZ with 0.074 KMD.
2) and one trade made successfully.
3) but my order is still active and listed on BUYER list.

`Don't auto-repeat order` is checked by default and I never click any option on that.

**Comment by satindergrewal** [comment]
In that case, it is not GUI issue, if it is still using the same 'buy' API call and repeating.
ask jl777 about this. or shossain or cipi in Slack.
