### ISSUE TITLE
Ledger hardware wallet trading support

### ISSUE THREAD

**Issue by psimondo** [KomodoPlatform/BarterDEX#72]
Been playing with radar replay. There is something pretty magical about trading straight off your ledger . A similar feature for BarterDex would be amazing, especially as KMD/ZEC and soon HUSH/ZEN will have Ledger support.

**Comment by satindergrewal** [comment]
Please request this to @jl777

**Comment by psimondo** [comment]
how do I send it directly to @jl777? via another repository like SuperNet rather than BarterDex?
