### ISSUE TITLE
Straks (STAK) in native mode doesn't work

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/BarterDEX#77]
Straks wallet is fully synched but when enabling it in native mode, BarterDex complains it can't find the coin (issue reported by an user)

**Comment by satindergrewal** [comment]
Please ask the user to delete `coins.json` file from BarterDEX's data directory, then restart BarterDEX and then try again using STAK. It should work.

**Comment by cipig** [comment]
1. wallet-config has to be in default location
2. wallet-config must contain at least these options
```
server=1
rpcuser=whatever
rpcpassword=whatever
```
3. the wallet must listen to the default rpcport (7574 for STAK and 9332 for LTC)

if one of the above is not true, BarterDEX has no chance talking to the wallet, so i would check that first.
