### ISSUE TITLE
Blocknet (Block) in native mode doesn't work

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/BarterDEX#78]
Full Blocknet wallet installed on Ubuntu 17.10 and completely synched, when enabling it in native mode BarterDex says "Coin status: coin can't be activated till synched"

**Comment by cipig** [comment]
These are the steps i have done to get BLOCK wallet running
```
git clone https://github.com/BlocknetDX/BlockDX
cd BlockDX
./autogen.sh
./configure --with-incompatible-bdb --with-gui=no --disable-tests --disable-bench --without-miniupnpc
make -j4
sudo make install
mkdir ~/.blocknetdx
echo "server=1" >> ~/.blocknetdx/blocknetdx.conf
echo "litemode=1" >> ~/.blocknetdx/blocknetdx.conf
echo "staking=0" >> ~/.blocknetdx/blocknetdx.conf
echo "listen=0" >> ~/.blocknetdx/blocknetdx.conf
echo "rpcuser=barterblock" >> ~/.blocknetdx/blocknetdx.conf
echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >> ~/.blocknetdx/blocknetdx.conf
chmod 0600 ~/.blocknetdx/blocknetdx.conf
blocknetdxd -daemon
```
after that, wait for chain to sync, start barterdex and send coins to the BLOCK smartaddress

So you need a running BLOCK wallet with config in the default location and containing at least this options "server=1, rpcuser=whatever, rpcpassword=whatever". The wallet must be listening to the default rpcport (41414).
On Linux you can check this easily:
`curl --user <username> --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:41414/`
Use the value of rpcuser from wallet config as <username> and the value of rpcpassword when it asks for a password. The above command must return something, else BarterDEX has no chance talking to the wallet.
