### ISSUE TITLE
Sent Hush token to the BarterDex and not showing up

### ISSUE THREAD

**Issue by Bitman514** [KomodoPlatform/BarterDEX#79]
I sent small amount to test it I see the tokens on explorer but not in BarterDex these issues should've been fixed before launch lol

**Comment by satindergrewal** [comment]
confirm if you are getting the same address in barterdex to which you sent the address to.
you'll always get the same address if you use the same passphrase/seed.

If using HUSH Electrum, then there can be some delays in response from Electrum servers. You can try disabling and enabling back the HUSH coin again and check if you get the reply.

The best solution is to use Native HUSH wallet and add HUSH as Native coin in BarterDEX.

Try these options. Hope this helps.
