### ISSUE TITLE
"Enable auto-repeat" option with BUY problem.

### ISSUE THREAD

**Issue by goldenman-kmd** [KomodoPlatform/BarterDEX#8]
![image](https://user-images.githubusercontent.com/33863358/34115232-5f6a3f3a-e458-11e7-99c3-69d750ee4641.png)

version : 0.7.7 released version

OS : Tried with Windows 10 And Ubuntu(Linux)

steps
 1. click one of seller's orders
 2. check the amounts and click `Enable auto-repeat this trade` checkbox and hit BUY
 3. my order listed on BUYERS list. but number of `Price in KMD` is not normal.
 4. I found Bid of KMD and Ask of CHIPS is switched.

Expected : 
  buy with 0.4944332 (Price in KMD)

Problem : 
  buy with 20.22517905 (Price in KMD)

**Comment by satindergrewal** [comment]
pushed its possible fix in latest commit, did test with same values and it worked fine to my tests.
Closing this issue for now. Just comment on it again if the issue still exists. I'll reopen this issue and work on it.

Thanks
