### ISSUE TITLE
Use Layman terms

### ISSUE THREAD

**Issue by austusross** [KomodoPlatform/BarterDEX#82]
For maximal adoption, Barterdex needs to use layman terms.  Grandma should be able to use Barterdex. 
 Mathematically, some may understand the Bid/Ask terminology.  But everyone understand the layman terms:  Buy, Sell, Offer, Accept

For example:
Buy BTC                      / Sell BTC
Max Price to Offer      / Min Price to Accept
Max Amount to Buy   / Max Amount to Sell

This would replace:
Bid BTC                      / Ask BTC
Max Price to Bid       / Min Price to Ask
Max Amount to Bid / Max Amount to Ask

**Comment by austusross** [comment]
I made changes.

[en_US.json.txt](https://github.com/KomodoPlatform/BarterDEX/files/1671687/en_US.json.txt)

**Comment by austusross** [comment]
I edited the file in a fork so that it can be merged with minimal fuss ... this issue of layman-izing probably applies to other languages as well.  I'm sure grandmas of every language would like to get themselves some Komodo without learning day trader speak.

**Comment by satindergrewal** [comment]
thanks merged
