### ISSUE TITLE
Electron vulnerability

### ISSUE THREAD

**Issue by AlexandrPy** [KomodoPlatform/BarterDEX#84]
https://www.cyberscoop.com/electron-vulnerability-skype-slack/

**Comment by cipig** [comment]
This affects only the electrum client. Barterdex uses his own electrum-client-implementation and is not affected.

**Comment by imylomylo** [comment]
Electon is the multi desktop framework.
Not electrum.

Affects custom links.  Maybe linking to the explorer where it opens a new window is affected.

**Comment by AlexandrPy** [comment]
Sorry, if it was the wrong topic.
