### ISSUE TITLE
Change Order types

### ISSUE THREAD

**Issue by siulynot** [KomodoPlatform/BarterDEX#85]
![image](https://user-images.githubusercontent.com/225342/35570892-e8f86280-05a6-11e8-86bd-4537fb83d2f8.png)

In centralized exchanges the order types for buying or selling are: "Market" or "Limit" orders. 

In my opinion, the "Do not auto-repeat order can be called a "Market Order". It virtually does the same thing, that is, dumping the order at market price. 
Then the "enable auto-repeat for this trade" should be called a "Limit Order". The same thing with a limit order, the fixed autoprice command just sets an order in the orderbook waiting to be filled by someone. 
Then, there is "enable auto-repeat & coinmarketcap price". This one should be called "Market Maker" since that is what it does. 

I think these changes will help people coming from centralized exchanges better understand the dynamics of the order types.

**Comment by barterjoe** [comment]
While I agree with this point, it would be great to have info bubbles for novice users to help explain the meanings. 
Great work guys!
