### ISSUE TITLE
bDEX 0.87  Don't see the same balance in dashboard and exchange tab

### ISSUE THREAD

**Issue by 27aume** [KomodoPlatform/BarterDEX#86]
Hi, I was building UTXOs and then balance stopped updating in dashboard but not exchange.

![image](https://user-images.githubusercontent.com/30743589/35599782-d0628cb4-0600-11e8-9d95-1b974a5cb4d9.png)

Restarting barterDex solve the issue, just reporting.

**Comment by satindergrewal** [comment]
That is barterDEX core issue. If happen again, please consult with @jl777.
Thanks for reporting.
