### ISSUE TITLE
GUI 8.8rc Splitter - GUI needs restarted when switching to a different coin

### ISSUE THREAD

**Issue by nostrakhan** [KomodoPlatform/BarterDEX#89]
If I use the new splitter on a certain coin the first time it works great.  Then if I switch to a different coin and try the splitter, in the confirmation window it shows the coin that I was previously splitting.  If I restart the GUI and start with my 2nd coin then the confirmation window shows the correct coin for splitting.

**Comment by satindergrewal** [comment]
https://github.com/KomodoPlatform/BarterDEX/issues/96
