### ISSUE TITLE
Newest "Enable auto-repeat this trade" has major bugs.

### ISSUE THREAD

**Issue by TheComputerGenie** [KomodoPlatform/BarterDEX#9]
`Buy` makes you a seller
![buy](https://user-images.githubusercontent.com/21057518/34193055-56fa6d74-e517-11e7-9d2a-8156a8a8fd4f.JPG)

`Sell` makes you a buyer and contains the previous buy bug
![sell](https://user-images.githubusercontent.com/21057518/34193070-73123550-e517-11e7-929f-228f8813264f.JPG)

**Comment by jansako** [comment]
Confirming the auto-repeat bug... it posts an opposite order... wow, but cancelling & submitting it again the exact same way it did post the correct one... that is not good!

**Comment by TheComputerGenie** [comment]
Fixed with https://github.com/KomodoPlatform/BarterDEX/commit/f0c721435aa4ee233a8169b086fcee27d144fe8c
