### ISSUE TITLE
Transaction wont send out of Barterdex

### ISSUE THREAD

**Issue by jb1215** [KomodoPlatform/BarterDEX#90]
Keeps saying Transaction error and not showing my balance when sending of 54 HUSH which i sent it yesterday

**Comment by gonzalezea** [comment]
Same here but with HUSH. Sent 4 transactions (100+conf) to address in electrum mode & only first one was received. Seems some kind of sync problem with network. So far haven't found any msg in log that give some clue or how to resync.

[HUSH address](https://explorer.myhush.org/address/t1eUctvouuyo93KzAv5PoCVVYX8w8gh4pem)

Ubuntu 16.04.4 x64
Barterdex 0.8.9-rc

**Comment by siulynot** [comment]
Can you try with the newest release and see its fixed?

**Comment by gonzalezea** [comment]
Great, now it works with v0.8.13-rc !! balance now is correct, thx.
