### ISSUE TITLE
Order x3 more expencive then expected.

### ISSUE THREAD

**Issue by 27aume** [KomodoPlatform/BarterDEX#92]
Hi, I've placed a manual trade and the result was that I've paid x3 my `max price to pay` setting.
the order was a `bid`+` manual trade` `auto-repeat this trade` at `3.101` kmd by REVS
max amount to buy: `0.29` REVS 
      total KMD to pay `0.99~`

The result we're:
Price payed `10.11..~` KMD by REVS
and i received `0.0702..~`
 total payed `0.7` KMD

The trade it self dont bother me (test purpose KMDs)
I'm aware that we are doing UTXO matching.

I splited a 20 KMD in  UTXOS of 0.25 , 0.5 and 0.99~ KMD 

My idea is that seen both UTXOS were really small) it just matched 2 random UTXOs without taking in count some of the rules that were set (max price).

![x3 price paied](https://user-images.githubusercontent.com/30743589/35722173-9c97a0be-07cb-11e8-817d-6b07615778c7.jpg)

**Comment by 27aume** [comment]
Sorry here the info in txt so it can be copied:
Quote id: 1049950419

Request id 2369154503
trade id 4050603893

buyer id 12705562534869073921
buyer pay. 8dc177d4a01818b28d2819bdaad063cf313cf6a418a24a359193647635dabf5c


Sell dep: 431806abc6d7360ee0bcc75a05b7ae44c110690fd97f24c29ae0c65e24b680b5
sell pay. dabb5ecf55b3199a9cdadca52ec5480901915237788343919588699e96aaca4b

**Comment by satindergrewal** [comment]
This looks more like a Core issue than UI. Please consult with @jl777 on Slack.

**Comment by 27aume** [comment]
@satindergrewal Hi, just thinking wouldn't it be more efficient to add JL777 in here then send me to him.
Would help to make a report to be useful and all parties keep track of the subject.

like sharing the Issue ticket, so the other party see the actual tread. 
I think it would help make your time answering those tickets more useful, keep a good follow up on Issues/Ideas and avoiding very body repeating their self would be :
++ organization
++ result
-- time wasted
-- confusion
++ Productivity
Thank you, all my respect 👍
