### ISSUE TITLE
Couldnt connect to BCH electrum server

### ISSUE THREAD

**Issue by DeniaZabar** [KomodoPlatform/BarterDEX#93]
You have this error in last 3 or more releases. BCH electrum server couldn't connect. Cant trade in any coin to BCH.

**Comment by cipig** [comment]
BCH electrum servers are stopped because the do not support the new BCH address format. For BCH, wou will need the native wallet.

**Comment by DeniaZabar** [comment]
Thanks for info :) Do you planing to eventualy enable BCH electrum in new releases?

**Comment by cipig** [comment]
BCH electrum servers are running again.
