### ISSUE TITLE
BTC withdraw and UTXO Split not working

### ISSUE THREAD

**Issue by himu007** [KomodoPlatform/BarterDEX#96]
BrterEX GUI can't show any BTC balance for UTXO split and withdraw. CLI is working fine with BTC `withdraw` function. 
Also, inventory management using electrum shows 0 balance in the top-left corner most of the time. Thus, users are not able to split their inventory.

![test](https://user-images.githubusercontent.com/8881040/35766446-c38b88c4-08d0-11e8-9ea1-e811dcb6e46d.jpg)

**Comment by tedy5** [comment]
Having the same problem with all coins, not just BTC.
Fresh Ubuntu 16.04 on VirtualBox.

**Comment by gonzalezea** [comment]
Same here with all coins I have (KMD & ZCL), restart change nothing

w10-x64
BarterDEX v0.8.8-rc

**Comment by satindergrewal** [comment]
Latest commits have utxo splitter bug fixes. please open the issue again still issues.
