### ISSUE TITLE
Age of order reset

### ISSUE THREAD

**Issue by goldenman-kmd** [KomodoPlatform/BarterDEX#99]
Version : 0.8.8
OS : Windows 10

Steps
1. Put ASK of BEER coin
2. Put ASK of HUSH coin

when I put or update any order of HUSH, then age of BEER coin is reset to '0'

**Comment by satindergrewal** [comment]
Age is not something UI sets. Age only means for how long the order is active, in terms of seconds. The average time for an order be active is 60 seconds.
If still have confusions, please get help from #tradebots channel in Slack.
